# Generated by Django 2.2.3 on 2023-11-14 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.CharField(max_length=75)),
                ('portion', models.CharField(max_length=10)),
                ('units', models.CharField(max_length=10)),
                ('gross_weight', models.CharField(max_length=6)),
                ('net_weight', models.CharField(max_length=6)),
                ('energy', models.CharField(max_length=6)),
                ('carbs', models.CharField(max_length=6)),
                ('clasification', models.CharField(max_length=75)),
            ],
        ),
    ]
