# Generated by Django 2.2.3 on 2023-11-11 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
