runtime: python311
entrypoint: gunicorn -b :$PORT glucosapp.wsgi

env_variables:
  DJANGO_SETTINGS_MODULE: "glucosapp.settings"

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
