# Generated by Django 2.2.3 on 2023-11-01 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='units',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
